/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
/home/daito/analyzing-tied-weights-nn/weights_analysis.py:67: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(checkpoint_path)
Layer: inconv.weight
tensor([[[[ 0.0726,  0.1901, -0.0194],
          [ 0.1944,  0.4011,  0.1550],
          [-0.0278,  0.1417, -0.1057]]]], device='cuda:0')
Layer: outconv.weight
tensor([[[[ 0.0726,  0.1901, -0.0194],
          [ 0.1944,  0.4011,  0.1550],
          [-0.0278,  0.1417, -0.1057]]]], device='cuda:0')
[[ 0.07258267  0.19007586 -0.01937882]
 [ 0.19437045  0.40107635  0.15503748]
 [-0.02777226  0.14168929 -0.10571981]]
1020
Traceback (most recent call last):
  File "/home/daito/analyzing-tied-weights-nn/weights_analysis.py", line 252, in <module>
    
NameError: name 'm' is not defined
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/daito/analyzing-tied-weights-nn/weights_analysis.py", line 19, in <module>
    from scipy import pinv
ImportError: cannot import name 'pinv' from 'scipy' (/home/daito/.local/lib/python3.10/site-packages/scipy/__init__.py)
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/daito/analyzing-tied-weights-nn/weights_analysis.py", line 19, in <module>
    from scipy import pinv
ImportError: cannot import name 'pinv' from 'scipy' (/home/daito/.local/lib/python3.10/site-packages/scipy/__init__.py)
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/daito/analyzing-tied-weights-nn/weights_analysis.py", line 19, in <module>
    from scipy import pinv
ImportError: cannot import name 'pinv' from 'scipy' (/home/daito/.local/lib/python3.10/site-packages/scipy/__init__.py)
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/daito/analyzing-tied-weights-nn/weights_analysis.py", line 19, in <module>
    from scipy import pinv
ImportError: cannot import name 'pinv' from 'scipy' (/home/daito/.local/lib/python3.10/site-packages/scipy/__init__.py)
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/daito/analyzing-tied-weights-nn/weights_analysis.py", line 19, in <module>
    from scipy import pinv


    
ImportError: cannot import name 'pinv' from 'scipy' (/home/daito/.local/lib/python3.10/site-packages/scipy/__init__.py)
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/daito/analyzing-tied-weights-nn/weights_analysis.py", line 19, in <module>
    from scipy import pinv
ImportError: cannot import name 'pinv' from 'scipy' (/home/daito/.local/lib/python3.10/site-packages/scipy/__init__.py)

